apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dfo-eks-cluster-1
  region: eu-central-1

vpc:
  id: "vpc-0c5afa7903c7aca62"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.220.36.0/22"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    private:
      eu-central-1a:
        id: "subnet-0edf19830fd73b002"
        cidr: "10.220.38.0/24" # (optional, must match CIDR used by the given subnet)

      eu-central-1b:
        id: "subnet-030ca07be691a4221"
        cidr: "10.220.39.0/24"  # (optional, must match CIDR used by the given subnet)


managedNodeGroups:
  - name: managed-ng-private
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 2
    maxSize: 4
    # launch nodegroup in private subnets
    privateNetworking: true
    labels: {role: worker}